# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet tests '
  enabled: true
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: 'custom'
    projects: 'src/SignalR.Orleans/SignalR.Orleans.csproj'
    custom: 'pack'
    arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) -p:IncludeSymbols=false -p:IncludeSource=false -p:PackageVersion=1.5.0.$(Build.BuildId) -p:PackageId=Mmm.SignalR.Orleans' 

- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '90a60c75-8236-43e9-bd2a-a9c0553b1af7'
